### ISSUE TITLE
BUG: Background color of Signup page having same color for both Light and Dark mode

### ISSUE THREAD

**Issue by kaali001** [Nactore-Org/Nacto-Care#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The background color of Signup page are same for both modes (light & Dark) .

In dark mode -
![image](https://github.com/Nactore-Org/Nacto-Care/assets/115466381/e02134c2-78ec-48ad-8ebd-f02502965ff7)

In light mode -
![image](https://github.com/Nactore-Org/Nacto-Care/assets/115466381/9cff915a-b138-4f1d-b403-c5b8407e3f34)

**Problem**

Both mode have same color as -

> background-color: #121212;

**Solution**

For light mode color should be same as in the light mode for login page -

> background-color: rgb(250 250 250 / var(--tw-bg-opacity));

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
#99  is almost similar but I think it's not at all duplicate. I hope the changes do not overlap so just commenting here to make it clear about two contributors working for the dark mode visibility on same page. This should probably help ahead to move forward quickly without raising merge conflicts.

@kaali001 @sharmi4590
