### ISSUE TITLE
BUG 🐞: Dark mode gets turned off on refeshing a page 

### ISSUE THREAD

**Issue by MastanSayyad** [Nactore-Org/Nacto-Care#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @Harshil-Jani, 

The **Dark mode** function gets turned off on refreshing a page or if we try to navigate to other pages through Footer. (You may check that) 

I think it is due to the theme state is not being persisted when the page is refreshed. As I have noticed in the `main.jsx` file, we are using `ReactDOM.createRoot` for rendering our app, which is a newer approach introduced in React

To fix this, we can store the theme state in the browser's local storage so that it persists across page reloads.

### Expected Solution:
When the `main.jsx` component is mounted, it will check the local storage for the saved theme and initialize the state accordingly. When the theme is toggled, it will update both the state and the local storage. 

This way, the dark mode will remain enabled even after refreshing the page. (As expected it to be)

### What are the benefits of this modification:

I believe by storing the theme state in the browser's local storage, we ensure that:
- The theme persists across page reloads and navigations
- Even when the user navigates away from the page, the theme persist
- This provides a seamless experience for users who prefer a specific theme setting. (for example, social media and our IDEs stay on the theme mode that we have selected)

I hope I was able to explain the issue and the expected solution. 
If so, Could you **please assign this issue to me under GSSoC 24**?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Sure. Controlling theme from local storage is good idea. Go ahead @MastanSayyad
