### ISSUE TITLE
Feat: Adding smooth scroll using Lenis

### ISSUE THREAD

**Issue by TenzDelek** [Nactore-Org/Nacto-Care#109]
### Describe the feature

gives a smooth feels when scrolling improving the user experience

### Add ScreenShots

uses Lenis

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by masterboy376** [comment]
Hello @Harshil-Jani I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine.

**Comment by Harshil-Jani** [comment]
Excited to see how that would look like. I have never tried Lenis. Let's see how it goes @TenzDelek
