### ISSUE TITLE
Auto Commenting when a PR is merged 

### ISSUE THREAD

**Issue by suhanipaliwal** [Nactore-Org/Nacto-Care#116]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by Harshil-Jani** [comment]
Finally yes. @suhanipaliwal , This is really cool idea. A thankful note would be loved when PRs are merged. I have been writing them manually but with automation I believe it will be much more helpful. Please go ahead.
