### ISSUE TITLE
[Frontend] : Implement `/blog` route and component on the website

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#12]
Just like standard website, We want to have a blog section where we can spin the articles related to nurse industry. While implementing the blog page you can keep lorem epsum dummy text and make sure it's somewhere in JSON. This will help us in future to add blogs directly from the backend infrastructure.

The design is upto the contributor. We have no objections and would love to see great ideas incoming.

**Comment by mohit-bhandari45** [comment]
want to work on this

**Comment by mohit-bhandari45** [comment]
created the blog route and blog page and linked the pr, you can check
