### ISSUE TITLE
[Backend] : Email and Phone Number should be unique in the database

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#13]

**Comment by Harshil-Jani** [comment]
@anujkumardarji Really sorry for missing information. I had #5 opened just for this reason. I have written most of the backend last night and forgot to add requirements file too. Damn !! Silly me.

I am adding that right now and replying here just in few mins.

**Comment by Harshil-Jani** [comment]
@anujkumardarji I have added requirements.txt file in the `/backend` directory.

Steps :
```
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
uvicorn main:app --reload
```

**Comment by anujkumardarji** [comment]
@Harshil-Jani Thank you 

I have created pull request #17  to address this issue. Please review and let me know if any further changes are needed.
