### ISSUE TITLE
BUG: changing SVG that are not suitable for Dark Mode

### ISSUE THREAD

**Issue by TenzDelek** [Nactore-Org/Nacto-Care#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

currently, some of the svgs are not visible for dark mode making it a visibility issue.
propose to change the svgs that are suitable for both mode
<img width="437" alt="image" src="https://github.com/Nactore-Org/Nacto-Care/assets/122612557/769dee34-3796-4aba-b5a9-134d8c91a689">
<img width="453" alt="image" src="https://github.com/Nactore-Org/Nacto-Care/assets/122612557/ffd0f73f-0090-400f-bddf-da554584b64f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Sure @TenzDelek
