### ISSUE TITLE
Feat: Adding Guidelines Page in the Brand Center

### ISSUE THREAD

**Issue by Hemashree21** [Nactore-Org/Nacto-Care#136]
### Describe the feature

@Harshil-Jani I want to work on this can you please assign this to me?

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/138188163/06513034-681c-4cfa-9d18-c43790881a00)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Just a small suggestion for the image on right if we can replace it with something more appealing to the light and dark theme of website.

**Comment by Hemashree21** [comment]
Okay I will change that
