### ISSUE TITLE
Feat: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [Nactore-Org/Nacto-Care#138]
### Describe the feature

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Add ScreenShots

![Close Old PRs](https://github.com/Nactore-Org/Nacto-Care/assets/115717746/00cd349f-7662-413e-a7fe-b1881ce4e1cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Harshil-Jani please assign me this issue

**Comment by Harshil-Jani** [comment]
Again same comment. Same are the opinions from the DJango community.
![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/1e59bbbb-e2b7-49df-af73-c88fc87ecc90)
