### ISSUE TITLE
Feat: Missing Feedback Form on Website

### ISSUE THREAD

**Issue by AkshitGarg24** [Nactore-Org/Nacto-Care#154]
### Describe the feature

**Problem:**

The website lacks a feedback form, which limits user interaction and prevents the collection of valuable user insights and suggestions.

**Solution:**

To address this issue, integrate a user-friendly feedback form. The form should include fields for:

- Name
- Email
- Rating (e.g., 1-5 stars)
- Comments/Suggestions

### Add ScreenShots

Below, you'll find images that provide an example of how the page will appear:

![Feedback1](https://github.com/Nactore-Org/Nacto-Care/assets/153659573/6c490ca7-5cb7-4959-825f-55ad1beedf7a)
![Feedback2](https://github.com/Nactore-Org/Nacto-Care/assets/153659573/1c779ff4-d805-4bfa-8a1b-830c3e6f3941)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Wouldn't the current contact us work ? We are thinking to take feedback from there itself as the description says
![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/14cf3b9c-d11c-483c-b11c-5476a25e2d24)

**Comment by AkshitGarg24** [comment]
To enhance user clarity, it's advisable to adopt the format depicted in the first image I've attached. Without this clarity, distinguishing between user-reported issues and feedback becomes challenging. In cases where users encounter problems, they can utilize the "Contact Us" option provided. However, for inquiries, suggestions, and general improvements, a dedicated feedback form should be made available.

**Comment by Harshil-Jani** [comment]
I see  @AkshitGarg24 . Let's give it a try how it turns out.
