### ISSUE TITLE
BUG: Broken CI activity for greeting.yml

### ISSUE THREAD

**Issue by TenzDelek** [Nactore-Org/Nacto-Care#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

the current greeting action is throwing error.
<img width="1237" alt="image" src="https://github.com/Nactore-Org/Nacto-Care/assets/122612557/ac65fe6b-c101-4f40-b2a9-ff559bf53f00">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Probably something with permissions in .yml file. Would be great if you can help find that.
