### ISSUE TITLE
Feat: Adding a hamburger opening animation

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Nactore-Org/Nacto-Care#179]
### Describe the feature

I want to add the smooth loading animation when hamburger will be clicked i think it will increase the UX .

### Add ScreenShots

https://github.com/Nactore-Org/Nacto-Care/assets/118350936/51043f2d-408a-43a5-aa7b-356301d84ee9

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Would love to see that @Ayushmaanagarwal1211
