### ISSUE TITLE
[Frontend] : On Clicking a blog card, Blog page should open

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#18]
@mohit-bhandari45 has worked on creating an awesome "Blog" Page and router to it. The next task on that page is to click on a particular card and open up the new page with the blog data in it with relevant styling.

![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/d74cd3b2-70a6-49a9-8528-fc7fac2339f7)

**Comment by mohit-bhandari45** [comment]
added a pr, you can check
