### ISSUE TITLE
[ENHANCEMENT] : Improving the contact page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Nactore-Org/Nacto-Care#187]
### Describe the feature

I think i can enhance the contact form by making the fields background a=of same colour and adding a white line below the input field and when user clicks on the field then the white lines shows with animation from 0 width to max width .

### Add ScreenShots

Before :
![Screenshot 2024-05-29 103927](https://github.com/Nactore-Org/Nacto-Care/assets/118350936/af2ed2fd-a708-4cfa-b0c5-62fd9c2e5112)
After 
![Screenshot 2024-05-29 103918](https://github.com/Nactore-Org/Nacto-Care/assets/118350936/a767d2c3-b087-4573-9aa9-51bb93243a49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
I don't think it sounds like a good change.
