### ISSUE TITLE
Feat:Adding better animations to send job application button

### ISSUE THREAD

**Issue by Stiffpixels** [Nactore-Org/Nacto-Care#192]
### Describe the feature

Right now the send job application button is bland and static:

I can add some custom hover animation which will make it pop

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/32983571/008d8d18-cd63-48ce-8658-fdf7e30541cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
This page is under re-vamp. It won't exist anytime later
Refer #104
