### ISSUE TITLE
[Frontend] : Make scroll bar green

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#2]
Currently the scroll bar on the right side of the screen is red in colour but we need that to be in accordance of the entire project theme. So task is to make it green.

![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/25303c04-15b5-4327-97bd-fdcca8225af2)

**Comment by Sky-De** [comment]
@Harshil-Jani hi, i would like to fix this for you, please assign this to me, thanks

**Comment by Harshil-Jani** [comment]
@Sky-De Sure. Go Ahead

**Comment by Harshil-Jani** [comment]
Completed by #4
