### ISSUE TITLE
BUG: The page requires smooth scrolling

### ISSUE THREAD

**Issue by aryansharma220** [Nactore-Org/Nacto-Care#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://github.com/Nactore-Org/Nacto-Care/assets/133234867/e825c5e8-8e8c-42dd-accc-50bc5b2d0f1c

The scrolling is not smooth.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Duplicate of #201
