### ISSUE TITLE
Feat: Adding a new 404 not found page in your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Nactore-Org/Nacto-Care#205]
### Describe the feature

Adding a new 404 not found page in your website

### Add ScreenShots

now its looks like something like this 
![image](https://github.com/Nactore-Org/Nacto-Care/assets/125277258/22dbc407-a373-4556-963f-c6b0f05b3084)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
It will be a good add-on @RamakrushnaBiswal . Looking forward to it.

**Comment by RamakrushnaBiswal** [comment]
solved #241
