### ISSUE TITLE
Feat:Adding tabs for different categories of blogs

### ISSUE THREAD

**Issue by Stiffpixels** [Nactore-Org/Nacto-Care#207]
### Describe the feature

We can split the blogs page into three tabs trending, latest and top blogs of the month

### Add ScreenShots

right now its just latest blogs:
![image](https://github.com/Nactore-Org/Nacto-Care/assets/32983571/e6672fcc-a064-4ad7-a71f-8b19eebf6102)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Would be great to see that coming @Stiffpixels
