### ISSUE TITLE
Feat:Improving the footer with good terms and conditions and privacy policy with updated location of the user to display and current time and thank you in differnet language 

### ISSUE THREAD

**Issue by Aksshay88** [Nactore-Org/Nacto-Care#208]
### Describe the feature

I would like to add the footer with more modern features and other stuffs .
![image](https://github.com/Nactore-Org/Nacto-Care/assets/119944779/508a7757-c09a-4776-a5df-f2ce172943ed)
https://main--macbookui.netlify.app/

you could check this website that I have been created 

![image](https://github.com/Nactore-Org/Nacto-Care/assets/119944779/5f816aa1-741d-481a-a1c9-6223022cc769)
Even I Could add this one 

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/119944779/b17b5244-0fa1-432a-aff3-954bd821af5f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
I feel that the current footer view is decent enough. For now , It seems out of scope for the project. You can take up some other task !!
