### ISSUE TITLE
DOC: Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by Maheshwari-Love** [Nactore-Org/Nacto-Care#212]
### What's wrong with the existing documentation

There is No instructions given for contributing to the project using GitHub Desktop.
There should also be the Step about how to contribute in the project using Github desktop as many of contributor's that.

### Add ScreenShots

Some thing like this

.

![image](https://github.com/Nactore-Org/Nacto-Care/assets/142833275/71084b4e-1515-4a8d-ab20-d732bdb702bf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@Harshil-Jani Can you please assign me this issue...

**Comment by Harshil-Jani** [comment]
@Maheshwari-Love I feel internet is open enough for people to discover new ways especially if they are into softwares. Either do by git cli or Github the core keywords remains the same. This would elongate the instruction guide and hide the more needful information away.

**Comment by Maheshwari-Love** [comment]
> @Maheshwari-Love I feel internet is open enough for people to discover new ways especially if they are into softwares. Either do by git cli or Github the core keywords remains the same. This would elongate the instruction guide and hide the more needful information away.

ok but in my view I found it easy to get the whole knowledge from on place ,if we are adding a document to refer then it should be clear and more informative so that user should not waste time to read 2-3 different documents
