### ISSUE TITLE
Feat: Dark Mode feature

### ISSUE THREAD

**Issue by mohit-bhandari45** [Nactore-Org/Nacto-Care#218]
### Describe the feature

So the website doesn't have any dark mode feature, I can add that.

Please assign me under gssoc24 and add a level3 label to it.

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/151373021/c0de86da-32f3-4e0d-9a4f-30dd5b298b35)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
@mohit-bhandari45 It seems you don't have the latest changes.
