### ISSUE TITLE
Feat: Adding the Service section

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#223]
### Describe the feature

When user clicks on service page they should get two options

Book your HomeCare (with an AI generated pic of nurse somewhere)
Find a patient (with an AI generated pic of patient somewhere)
But on the top there should be an option to select a city. By default you can keep any specific city selected and store that the latest selection in a local storage. Based on the city selected and the service selected, We need another two pages which will list out all the list of patients and nurses from that city. For now don't worry about the data, just put dummy data in it.

But the whole idea is

![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/b48ffa0c-86b5-4f88-b96d-df739f609252)

I think that this could be an Level 3 task and you can spend enough efforts for it. If you feel this is going to be too much for a single PR you can divide in 2 PRs of level-2. Let me know what are your thoughts on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Harshil-Jani** [comment]
@Hemashree21 Wait for a "reasonable response" in previous issue till afternoon. If we find nothing serious just start with it and feel free to discuss here.

**Comment by AkshitGarg24** [comment]
Hi @Harshil-Jani ,

I am interested in solving this issue but I have a question:

Should we add a new "Services" option in the navbar, or should we replace the existing "Book Nurse" option on the main page with "Services"?

**Comment by Hemashree21** [comment]
@Harshil-Jani I think I can complete it in a single PR of level 3. If I click the book homecare or the find patients button, should I redirect the responses to a different page or can I display the data below in the same page?

**Comment by Harshil-Jani** [comment]
@Hemashree21 Totally upto you. As long as we can render the different services it works. Whichever feels easier to maintain and implement to extend future functionalities.
