### ISSUE TITLE
BUG: Pictures not showing on the main page

### ISSUE THREAD

**Issue by kashnx** [Nactore-Org/Nacto-Care#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/Nactore-Org/Nacto-Care/assets/148524648/8d8ddeb5-8901-4f36-bb0e-a4ff283fa0ec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Closed with #233
