### ISSUE TITLE
Feat:Add Hover effects on footer's connect icons.

### ISSUE THREAD

**Issue by zalabhavy** [Nactore-Org/Nacto-Care#266]
### Describe the feature

I want to give hover effect to footer's connect icons.
it will looks good.

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/126322584/a49ff28e-0f87-4ef5-987a-d311853f60db)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Harshil-Jani can you please assign me this task.

**Comment by jayanththalla** [comment]
please assign me @pa i will add the more social media icons and hover it with different color.
i improve the footer with remove underline and hover the text

**Comment by Tanishka023** [comment]
Hey @Harshil-Jani Please assign this to me under GSSoC'24, I can fix this easily.
