### ISSUE TITLE
Fixing the footer 

### ISSUE THREAD

**Issue by agxmbedi** [Nactore-Org/Nacto-Care#31]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!
![Uploading Screenshot 2024-05-10 at 10.41.54 PM.png…]()

**Comment by aditya7483thakur** [comment]
Hello Sir ! Can you assign this issue to me

**Comment by mohit-bhandari45** [comment]
I want to work on this issue under gssoc24 @mohit-bhandari45

**Comment by Mohammad-Qamar** [comment]
Hi @Harshil-Jani  i have seen that footer is not looking good and very down touch ed bottom of display i think i can make it look good  and also i suggest there will be all social media icon with link  should come in footer that will look great 
i am here as a Contributor  GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by Harshil-Jani** [comment]
Hey @aditya7483thakur @Mohammad-Qamar @mohit-bhandari45 Give me a ping. I was not on my laptop because I was on a trip. Since it has been multiple days, I am not sure who would be still active enough to pick up the issue. Just ping me here in comments and I can assign this.

**Comment by Ayush170803** [comment]
Kindly assign me this issue, so i can work towards it under GSSoC'24. Thank You

**Comment by Harshil-Jani** [comment]
Go ahead @Ayush170803

**Comment by mohit-bhandari45** [comment]
Please assign me under gssoc24

**Comment by Harshil-Jani** [comment]
@mohit-bhandari45 Please pick some other issue. @Ayush170803 is working on it.
