### ISSUE TITLE
[Feature]: On hovering over the navbar elements, the size of the should increase

### ISSUE THREAD

**Issue by mohit-bhandari45** [Nactore-Org/Nacto-Care#33]
Description:- When hovering on the elements like home contact and more in navbar, they should increase their size with a beautiful animation.

Steps to reproduce:-
Step 1:- Go to the landing page
Step 2 :- hover over the navbar elements

Please assign this to me under gssoc24 @Harshil-Jani

**Comment by Harshil-Jani** [comment]
Sure @mohit-bhandari45 . Please go ahead.
