### ISSUE TITLE
[Frontend]: Non Functional Menu Icon in Mobile Screens

### ISSUE THREAD

**Issue by PranavKeshav24** [Nactore-Org/Nacto-Care#34]
##Description
The menu icon in Mobile S(320*592 px), Mobile M(375*592 px), Mobile L(425*592 px) screens to open up the menu containing the options ‘Component’, ‘Template’ and ‘Docs’ is non-functional, i.e., nothing happens when the icon is clicked.

##Steps to Reproduce
1.	Go to the website in a mobile device or set the screen size to mobile screen in inspect.
2.	Click on the hamburger button in the top right.
3.	It doesn’t work.

##Expected Behaviour
When the hamburger button is clicked, a menu containing the options ‘Component’, ‘Template’ and ‘Docs’ should be displayed.

##Actual Behaviour
Nothing happens upon clicking the hamburger icon (menu icon).

##Screenshots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/127531721/a57b3b2b-6e06-4104-abfc-c284d174cfe2)

##Environment
Operating System: Windows 10
Browser: Chrome 

##Additional Information
I am a contributor in GSSOC’ 24. Please assign me this issue, I would love to work on it.

**Comment by mohit-bhandari45** [comment]
I also want to work on the issue @Harshil-Jani. Assign this to me under gssoc24

**Comment by Harshil-Jani** [comment]
@PranavKeshav24 Could you still work on it ? If not then @mohit-bhandari45 Could you pick this up ? Let me know if you are available. Looking forward to see the change.

**Comment by PranavKeshav24** [comment]
@Harshil-Jani I can surely work on this issue. Please assign it to me.

**Comment by Harshil-Jani** [comment]
Sure. Go ahead @PranavKeshav24

**Comment by PranavKeshav24** [comment]
@Harshil-Jani Thank you for assigning the issue to me :)! I'll start working on it

**Comment by PranavKeshav24** [comment]
@Harshil-Jani I've resolved the issue and submitted a pull request in #73 . Could you review it and share your feedback?
