### ISSUE TITLE
Add Code of Conduct File

### ISSUE THREAD

**Issue by mdazfar2** [Nactore-Org/Nacto-Care#51]
### 🔖 Feature description

I'm reaching out to suggest improvements to the Code of Conduct file in your project. The current file lacks clarity and structure, making it challenging for readers to understand easily.

### 🎤 Why is this feature needed ?

- **Clarity**: Enhancing the document's organization will ensure clear guidelines.
- **Accessibility**: A well-structured file is easier for all contributors to comprehend.
- **Inclusivity**: A clear Code of Conduct promotes a welcoming community.

### ✌️ How do you aim to achieve this?

I aim to achieve this by restructuring the content for better organization, simplifying language to improve readability, and incorporating clear examples to illustrate expected behaviors. These changes will enhance the overall clarity and accessibility of the Code of Conduct.

### 🔄️ Additional Information

- Our Pledge
- Our Standards
- Examples of behavior that contributes to a positive environment for our community include:
- Examples of unacceptable behavior include:
- Enforcement Responsibilities
- Scope
- Enforcement

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Harshil-Jani** [comment]
Go ahead @mdazfar2
