### ISSUE TITLE
BUG: Password not masked in confirm Password section

### ISSUE THREAD

**Issue by Paper-Bag-dev** [Nactore-Org/Nacto-Care#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**To Replicate:**
When signing up and entering the password in the confirm password section. The entered values are not being masked or hidden.

**Screenshots**
![image](https://github.com/Nactore-Org/Nacto-Care/assets/92173476/c6bf3359-4bd5-4baa-befd-9b66a8e68d32)

**Fix:**
- Changing the input type of the password from "confirm-password" to "password"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Go ahead @Paper-Bag-dev

**Comment by gopalepic** [comment]
can i work on this issue , already face the same issue in my projects and can be solved easily

**Comment by Paper-Bag-dev** [comment]
Sorry this issue has been already resolved

**Comment by gopalepic** [comment]
@Harshil-Jani  , is this issue already solved

**Comment by Harshil-Jani** [comment]
Yes @gopalepic . You can check it on live website by yourself to verify if any issue is pending or solved. In this case, I remember merging a PR by @Paper-Bag-dev. So it has been resolved.
