### ISSUE TITLE
Add Legal pages: "Privacy Policy, Licensing and Terms & Conditions"

### ISSUE THREAD

**Issue by MastanSayyad** [Nactore-Org/Nacto-Care#56]
### Describe the feature

Currently, the NactoCare website has links to "Privacy Policy," "Licensing," and "Terms & Conditions" in the footer, but these links do not lead to actual pages.

I would like to take on this task and contribute to the development of the NactoCare website 
could you please assign this issue to me under GSSOC 24?

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/101971980/bcb9b6c8-98f0-49aa-8d97-bfe5f0814b5d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
That would be really helpful @MastanSayyad .
