### ISSUE TITLE
Feat:

### ISSUE THREAD

**Issue by Rhythm1710** [Nactore-Org/Nacto-Care#68]
### Describe the feature

Hi! I can refractor the backend code for more visibility and improved understanding.

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/65298117/91f4f136-23cd-4a5e-a9a5-3c4107aa9e78)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Harshil-Jani** [comment]
We can refactor once the codebase grows enough :) Tradeoff between time vs progress is real.
