### ISSUE TITLE
[Frontend] : New Route `/book` when Book Nurse Button is pressed.

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#8]
On pressing Book Nurse Button, It should navigate to a new route `/book-nurse`. For time being, You can place the component of Find your Home Care Tracker as it is on the new page.

![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/ffd75ac4-77be-4220-a9af-5ff3ccd1caa7)

**Comment by mohit-bhandari45** [comment]
want to work upon it as well

**Comment by Harshil-Jani** [comment]
Sure go ahead @mohit-bhandari45 🚀

**Comment by mohit-bhandari45** [comment]
Opened a PR, you can check
