### ISSUE TITLE
HIDDEN BUG: Routes Navigation link errors for the pages

### ISSUE THREAD

**Issue by MastanSayyad** [Nactore-Org/Nacto-Care#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey, as I have developed the legal pages for Nacto Care, 

![image](https://github.com/Nactore-Org/Nacto-Care/assets/101971980/cb370da8-87e4-451d-af8e-8105ab2ce9cc)

I was just checking my work After deployment and I found that The navigations to the pages don't work, after clicking it shows the following error

![image](https://github.com/Nactore-Org/Nacto-Care/assets/101971980/e6420c13-8251-4a27-b79c-1abe27c38283)

**It shows a 404 page.**

### **#Solution 1:**

- First, we will try by minor changing the path for the pages.

### **#Solution 2:**

After deploying the changed path if the error occurs again then based on my knowledge it only happens if you don't configure your `vercel.json` The routes don't get recognized except the "/" Home page routes. we have to:
-  Add a `vercel.json` file to the project.
- add these lines `{ "rewrites": [{ "source": "/(.*)", "destination": "/" }] }`
- On the vercel deployment dashboard ensure we pick vitejs as a framework 

## **Edit:**
I have checked for the other Page routes such as "careers/blogs/contacts/about/login/signup/book nurse" These URLs/Links only work for a short time, when you refresh the page, **it shows a 404 page.** (You can check that). 

![image](https://github.com/Nactore-Org/Nacto-Care/assets/101971980/5ca0e5ef-9fe8-46f8-8173-079305f4fed0)

![image](https://github.com/Nactore-Org/Nacto-Care/assets/101971980/4c09d56e-2fd3-420a-acd7-0214cf3bc3af)

Maybe most of the users or contributors didn't realize it. We can call it a **Hidden BUG** which can lead to a failed user experience and a bad impression.

I would like to take care of all these pages' Navigation errors.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Woah !! @MastanSayyad We didn't saw that coming. Thanks a lot for identification. Please go ahead with this.

**Comment by MastanSayyad** [comment]
@Harshil-Jani you can close this issue as completed.
