### ISSUE TITLE
Feat: Adding AI chatbot 

### ISSUE THREAD

**Issue by antriksh-9** [Nactore-Org/Nacto-Care#88]
### Describe the feature

An AI chatbot on Nacto Care website can provide 24/7 customer support, offer healthcare information. 
The chatbot can ask preliminary questions to understand the user’s needs and direct them to the appropriate healthcare professional.
The chatbot can provide users with information about different types of care, insurance coverage, and other services.

### Add ScreenShots

![Screenshot 2024-05-21 013906](https://github.com/Nactore-Org/Nacto-Care/assets/132576984/41eeb4d3-ecfd-406d-949f-e03c4b2833dd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
@antriksh-9 What service are you thinking to use ? Kommunicate or OpenAI APIs ? At the moment, We are not putting this up in priority but if you can suggest some service which can be easy to integrate and use I am happy to have it sooner or later.

**Comment by antriksh-9** [comment]
> @antriksh-9 What service are you thinking to use ? Kommunicate or OpenAI APIs ? At the moment, We are not putting this up in priority but if you can suggest some service which can be easy to integrate and use I am happy to have it sooner or later.

I have used [botpress ](https://botpress.com/)to integrate bot in a Blood Donation website, it's easy to integrate. Just I have to make the conversation workflow, add knowledge base

Here's the demo:

https://github.com/Nactore-Org/Nacto-Care/assets/132576984/3b9529b5-ca46-4be6-bb21-55aba826f0c2
