### ISSUE TITLE
[Frontend] : Learn More button should be fixed

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#9]
![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/adec5a52-a24e-41cb-8cce-5263396c4bee)

Here if you press "Learn More" button then it will redirect to `/about` which is no longer intended behaviour. Please re-direct it to the section which is in below screenshot.

![image](https://github.com/Nactore-Org/Nacto-Care/assets/79367883/7e751b44-3698-40b9-8a32-a9bfcffb5daf)

**Comment by ssaikumar65** [comment]
Fixed the Learn More button issue and raised PR #15.
