### ISSUE TITLE
BUG: Login and Signup Pages Height Issue 

### ISSUE THREAD

**Issue by DonaldReddy** [Nactore-Org/Nacto-Care#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In smaller screens, the login and signup components overlap with the footer.

![image](https://github.com/Nactore-Org/Nacto-Care/assets/83972294/050eab26-6060-4fd1-b156-7f4173fd3df5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Go ahead @DonaldReddy

**Comment by DonaldReddy** [comment]
@Harshil-Jani please assign this issue to me.
