### ISSUE TITLE
BUG: Toggle Button Does Not Automatically Close When Clicking on Login/Signup Buttons in Mobile View

### ISSUE THREAD

**Issue by kaali001** [Nactore-Org/Nacto-Care#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In the mobile view of the website, when clicking on the Login or Signup buttons in the navbar, the toggle button does not automatically close. This results in the toggle menu remaining open even after selecting one of the options, causing a poor user experience.

![image](https://github.com/Nactore-Org/Nacto-Care/assets/115466381/6efd7fb2-bebe-4a29-84dc-e838880198c7)

As a GSSOC'24 contributor, I would like to work on resolving this issue. Please assign it to me so that I can start working on this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Good catch @kaali001 . Please go ahead with this.
