### ISSUE TITLE
BUG: The UI of Career and About section is not responsive for the mobile screens

### ISSUE THREAD

**Issue by SnehansuBehera** [Nactore-Org/Nacto-Care#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Career and about section breaks at mobile screen widths, the ui needs to be made responsive by providing proper alignment (i.e, padding, spacing, etc) for better user experience.

![Screenshot 2024-05-21 141447](https://github.com/Nactore-Org/Nacto-Care/assets/121883802/8a64e81e-b644-417c-ab71-414a85eb3c3d)
![Screenshot 2024-05-21 141541](https://github.com/Nactore-Org/Nacto-Care/assets/121883802/f467d1ca-a03d-4ded-a068-c37b496b95e7)

hey @Harshil-Jani please assign me the issue, i want to contribute to it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Sure @SnehansuBehera Go ahead.
