### ISSUE TITLE
BUG:Text not visible on dark mode

### ISSUE THREAD

**Issue by sharmi4590** [Nactore-Org/Nacto-Care#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The text and the image are not visible in the dark mode.
![Screenshot (445)](https://github.com/Nactore-Org/Nacto-Care/assets/102676949/8dc0f56d-f0e5-48bc-892d-a319dbd5ad3b)
![Screenshot (446)](https://github.com/Nactore-Org/Nacto-Care/assets/102676949/67dbf7fa-e79f-4988-8808-3607a269b278)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
Sure. Go ahead with this @sharmi4590
